"""One-shot script: download Google Fonts woff2 files and embed them as base64
inside templates/_fonts.css.j2. Re-run only when the chosen font stack changes."""
from __future__ import annotations

import base64
import re
import urllib.request
from pathlib import Path

# (family, url, weight, style)
# URLs point to the `latin` subset woff2 files served by fonts.gstatic.com.
# Looked up via the Google Fonts CSS2 API with a modern Chrome User-Agent on
# 2026-05-18. Re-run this script (and refresh URLs as needed) if Google bumps
# the font version path. Latin subset is sufficient for English PDF reports
# and keeps the embedded css small.
FONT_FILES = [
    # Instrument Serif (v5, latin)
    ("Instrument Serif", "https://fonts.gstatic.com/s/instrumentserif/v5/jizBRFtNs2ka5fXjeivQ4LroWlx-6zUTjg.woff2", 400, "normal"),
    ("Instrument Serif", "https://fonts.gstatic.com/s/instrumentserif/v5/jizHRFtNs2ka5fXjeivQ4LroWlx-6zAjjH7M.woff2", 400, "italic"),
    # Inter (v20, latin) — distinct static per-weight slices.
    # NOTE: Hitting the CSS2 API with `wght@400;500;600` returns the *variable*
    # font URL (single file, same path for every weight) which silently renders
    # all weights as 400 in WeasyPrint. Requesting each weight individually
    # (`wght@400`, `wght@500`, `wght@600`) forces Google to serve distinct
    # static slices — those are what we embed here.
    ("Inter", "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuLyfAZ9hiA.woff2", 400, "normal"),
    ("Inter", "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuI6fAZ9hiA.woff2", 500, "normal"),
    ("Inter", "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuGKYAZ9hiA.woff2", 600, "normal"),
    # IBM Plex Mono (v20, latin)
    ("IBM Plex Mono", "https://fonts.gstatic.com/s/ibmplexmono/v20/-F63fjptAgt5VM-kVkqdyU8n1i8q1w.woff2", 400, "normal"),
    ("IBM Plex Mono", "https://fonts.gstatic.com/s/ibmplexmono/v20/-F6qfjptAgt5VM-kVkqdyU8n3twJwlBFgg.woff2", 500, "normal"),
]

OUT_PATH = Path(__file__).resolve().parents[1] / "app" / "services" / "document_engine" / "templates" / "_fonts.css.j2"


def fetch(url: str) -> bytes:
    # Use a modern Chrome UA so fonts.gstatic.com serves the woff2 directly
    # (some custom UAs get redirected or 403'd).
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            )
        },
    )
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read()


def main() -> None:
    blocks: list[str] = ["{# AUTO-GENERATED by scripts/embed_fonts.py. Do not edit by hand. #}"]
    for family, url, weight, style in FONT_FILES:
        print(f"Fetching {family} {weight} {style} …")
        data = fetch(url)
        b64 = base64.b64encode(data).decode("ascii")
        blocks.append(
            "@font-face {\n"
            f"  font-family: \"{family}\";\n"
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            f"  font-display: swap;\n"
            f"  src: url(\"data:font/woff2;base64,{b64}\") format(\"woff2\");\n"
            "}"
        )
    OUT_PATH.write_text("\n\n".join(blocks) + "\n", encoding="utf-8")
    size_kb = OUT_PATH.stat().st_size // 1024
    print(f"Wrote {OUT_PATH} ({size_kb} KB)")


if __name__ == "__main__":
    main()
