import Link from 'next/link';
import LumidianLogo from '@/components/LumidianLogo';

export const metadata = { title: 'Terms of Service' };

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: `By creating an account or using Lumidian ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. These Terms apply to all users, including free and paid subscribers.`,
  },
  {
    title: '2. Description of Service',
    body: `Lumidian provides a platform that tracks how brands are mentioned in responses generated by large language models (LLMs) such as ChatGPT, Claude, Perplexity, and Gemini. The Service includes scheduled and on-demand visibility reports, trend analysis, and AI-assisted content drafting.`,
  },
  {
    title: '3. Accounts',
    body: `You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials and for all activity under your account. You must be at least 18 years old to use the Service. We reserve the right to suspend or terminate accounts that violate these Terms.`,
  },
  {
    title: '4. Subscriptions and Billing',
    body: `Paid plans are billed monthly. The 30-day free trial period begins on the date you subscribe to a paid plan. You will not be charged until the trial period ends. You may cancel at any time before the trial ends to avoid being charged. Refunds are not provided for partial billing periods. We reserve the right to change pricing with 30 days' notice.`,
  },
  {
    title: '5. Acceptable Use',
    body: `You agree not to use the Service to: (a) violate any applicable law or regulation; (b) infringe the intellectual property rights of others; (c) submit false, misleading, or fraudulent information; (d) attempt to gain unauthorized access to the Service or its underlying systems; (e) use the Service to track brands or entities you do not have authorization to represent; or (f) resell or redistribute the Service without our written consent.`,
  },
  {
    title: '6. Data and Privacy',
    body: `Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to the collection and use of data as described in the Privacy Policy.`,
  },
  {
    title: '7. Intellectual Property',
    body: `Lumidian and its licensors own all rights to the Service, including software, design, and documentation. You retain ownership of the brand data, prompts, and content you submit. By submitting content, you grant Lumidian a limited license to process and display it solely for the purpose of providing the Service to you.`,
  },
  {
    title: '8. Third-Party LLM Services',
    body: `The Service queries third-party AI platforms to generate visibility data. Lumidian is not affiliated with OpenAI, Anthropic, Google, or Perplexity. LLM responses are generated by those third parties and may vary in accuracy or availability. We do not guarantee that any particular AI platform will be available or return specific results.`,
  },
  {
    title: '9. Disclaimer of Warranties',
    body: `The Service is provided "as is" without warranties of any kind, express or implied. Lumidian does not warrant that the Service will be uninterrupted, error-free, or that visibility scores will be accurate or complete. AI model responses are probabilistic and may change over time.`,
  },
  {
    title: '10. Limitation of Liability',
    body: `To the maximum extent permitted by law, Lumidian shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability to you for any claim arising from these Terms shall not exceed the amount you paid us in the 12 months preceding the claim.`,
  },
  {
    title: '11. Changes to Terms',
    body: `We may update these Terms from time to time. When we do, we will revise the "Last updated" date below and, for material changes, notify you by email or an in-app notice. Continued use of the Service after changes take effect constitutes acceptance of the revised Terms.`,
  },
  {
    title: '12. Contact',
    body: `Questions about these Terms? Email us at legal@lumidian.ai.`,
  },
];

export default function TermsPage() {
  return (
    <div
      style={{
        minHeight: '100vh',
        backgroundColor: '#F8F7F4',
        color: '#0F0F12',
        fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      }}
    >
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap');`}</style>

      {/* Nav */}
      <nav style={{ borderBottom: '1px solid rgba(0,0,0,0.06)', padding: '16px 24px' }}>
        <div style={{ maxWidth: 760, margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 8, textDecoration: 'none' }}>
            <LumidianLogo size={28} withWordmark variant="light" />
          </Link>
          <Link href="/register" style={{ fontSize: 13, fontWeight: 600, color: '#4F46E5', textDecoration: 'none' }}>
            Get started →
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main style={{ maxWidth: 760, margin: '0 auto', padding: '64px 24px 96px' }}>
        <div style={{ marginBottom: 48 }}>
          <h1 style={{ fontSize: 36, fontWeight: 800, color: '#0F0F12', letterSpacing: '-0.03em', margin: '0 0 12px' }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 14, color: '#9CA3AF', margin: 0 }}>Last updated: March 27, 2026</p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
          {SECTIONS.map((section) => (
            <div key={section.title}>
              <h2 style={{ fontSize: 16, fontWeight: 700, color: '#0F0F12', margin: '0 0 10px', letterSpacing: '-0.01em' }}>
                {section.title}
              </h2>
              <p style={{ fontSize: 15, color: '#4B5563', lineHeight: 1.75, margin: 0 }}>
                {section.body}
              </p>
            </div>
          ))}
        </div>
      </main>

      {/* Footer */}
      <footer style={{ borderTop: '1px solid rgba(0,0,0,0.06)', padding: '24px' }}>
        <div style={{ maxWidth: 760, margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 }}>
          <p style={{ fontSize: 12, color: '#9CA3AF', margin: 0 }}>&copy; 2026 Lumidian. All rights reserved.</p>
          <div style={{ display: 'flex', gap: 20 }}>
            <Link href="/terms" style={{ fontSize: 12, color: '#9CA3AF', textDecoration: 'none', fontWeight: 500 }}>Terms</Link>
            <Link href="/privacy" style={{ fontSize: 12, color: '#9CA3AF', textDecoration: 'none', fontWeight: 500 }}>Privacy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
